export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_ALL_PRODUCT_BEST = 'GET_ALL_PRODUCT_BEST';
export const GET_ALL_PRODUCT_NEW = 'GET_ALL_PRODUCT_NEW';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const ADD_CART = 'ADD_CART' ;
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART = 'DELETE_CART';
export const DELETE_ALL_CART = 'DELETE_ALL_CART';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_PRODUCT_BY_CATEGORY = 'GET_ALL_PRODUCT_BY_CATEGORY';
export const GET_ALL_PRODUCT_BY_KEYWORD = 'GET_ALL_PRODUCT_BY_KEYWORD';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
